# Use the official Python image from the Docker Hub
FROM python:3.9-slim

# Set the working directory for the application
WORKDIR /app

# Copy the application into the container
COPY . .

# Install the dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Expose port 5000
EXPOSE 5000

# Command to run the application
CMD ["python", "src/app.py"]